# Generated by Django 4.0.5 on 2022-06-18 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 19, 10, 34, 23022)),
        ),
    ]
