# Generated by Django 4.0.5 on 2022-06-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0003_alter_autor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_nac',
            field=models.DateField(blank=True),
        ),
    ]
