# Generated by Django 4.0.5 on 2022-06-30 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0005_alter_autor_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='fecha_nac',
        ),
    ]
