# Generated by Django 4.0.5 on 2022-06-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0007_autor_fecha_nac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='fecha_nac',
            field=models.DateField(),
        ),
    ]
