# Generated by Django 4.0.5 on 2022-06-18 21:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField(default=datetime.datetime(2022, 6, 18, 18, 6, 5, 676628))),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to='autor.autor')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='noticia.noticia')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
